config/routes.rb
Rails.application.routes.draw do
  resources :refine_calculators
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/refine_calculator.rb
class RefineCalculator < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/refine_calculators_controller.rb
class RefineCalculatorsController < ApplicationController
  before_action :set_refine_calculator, only: %i[ show edit update destroy ]

  # GET /refine_calculators or /refine_calculators.json
  def index
    @refine_calculators = RefineCalculator.all
  end

  # GET /refine_calculators/1 or /refine_calculators/1.json
  def show
  end

  # GET /refine_calculators/new
  def new
    @refine_calculator = RefineCalculator.new
  end

  # GET /refine_calculators/1/edit
  def edit
  end

  # POST /refine_calculators or /refine_calculators.json
  def create
    @refine_calculator = RefineCalculator.new(refine_calculator_params)

    respond_to do |format|
      if @refine_calculator.save
        format.html { redirect_to @refine_calculator, notice: "Refine calculator was successfully created." }
        format.json { render :show, status: :created, location: @refine_calculator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @refine_calculator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /refine_calculators/1 or /refine_calculators/1.json
  def update
    respond_to do |format|
      if @refine_calculator.update(refine_calculator_params)
        @refine_calculator.url_image = (@refine_calculator.refine_fee.to_f / 100) * (100 - refine_calculator_params[:tax].to_f)
        @refine_calculator.save!
        format.html { redirect_to @refine_calculator, notice: "Refine calculator was successfully updated." }
        format.json { render :show, status: :ok, location: @refine_calculator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @refine_calculator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /refine_calculators/1 or /refine_calculators/1.json
  def destroy
    @refine_calculator.destroy
    respond_to do |format|
      format.html { redirect_to refine_calculators_url, notice: "Refine calculator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_refine_calculator
      @refine_calculator = RefineCalculator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def refine_calculator_params
      params.require(:refine_calculator).permit(:item, :value, :refined, :refine_fee, :transmutation_fee, :url_image, :tax)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/refine_calculators_helper.rb
module RefineCalculatorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlbionCalculator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/refine_calculators/_form.html.erb
<%= form_with(model: refine_calculator) do |form| %>
  <% if refine_calculator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(refine_calculator.errors.count, "error") %> prohibited this refine_calculator from being saved:</h2>

      <ul>
        <% refine_calculator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item %>
    <%= form.text_field :item %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :refined %>
    <%= form.text_field :refined %>
  </div>

  <div class="field">
    <%= form.label :refine_fee %>
    <%= form.number_field :refine_fee %>
  </div>

  <div class="field">
    <%= form.label :transmutation_fee %>
    <%= form.number_field :transmutation_fee %>
  </div>

  <div class="field">
    <%= form.label :url_image %>
    <%= form.text_field :url_image %>
  </div>

  <div class="field">
    <%= form.label :tax %>
    <%= form.text_field :tax %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/refine_calculators/edit.html.erb
<h1>Editing Refine Calculator</h1>

<%= render 'form', refine_calculator: @refine_calculator %>

<%= link_to 'Show', @refine_calculator %> |
<%= link_to 'Back', refine_calculators_path %>

app/views/refine_calculators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Refine Calculators</h1>
<br>
<br>
<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Valor de Mercador</th>
      <th>Refinado</th>
      <th>Taxa</th>
      <th>Custo</th>
      <th>Retorno</th>
      <th>Lucro</th>
    </tr>
  </thead>

  <tbody>
    <% @refine_calculators.each do |refine_calculator| %>
      <tr>
        <td><%= refine_calculator.item %></td>
        <td><input type="text" placeholder=<%= refine_calculator.value %>></td>
        <td><input type="text" placeholder=<%= refine_calculator.refined %>></td>
        <td><%= refine_calculator.refine_fee %></td>
        <td><%= refine_calculator.refine_fee * refine_calculator.value %></td>
        <td><%= refine_calculator.refine_fee %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<br>
---------------------------------------

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Value</th>
      <th>Refined</th>
      <th>Refine fee</th>
      <th>Transmutation fee</th>
      <th>Url image</th>
      <th>Valor Calculado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @refine_calculators.each do |refine_calculator| %>
      <tr>
        <td><%= refine_calculator.item %></td>
        <td><%= refine_calculator.value %></td>
        <td><%= refine_calculator.refined %></td>
        <td id="<%= refine_calculator.id %>_value"><%= refine_calculator.refine_fee %></td>
        <td><%= refine_calculator.transmutation_fee %></td>
        <td><%= refine_calculator.url_image %></td>
        <td><%= ((refine_calculator.refine_fee.to_f / 100) * (100 - refine_calculator.tax.to_f)).to_s %></td>
        <td><%= link_to 'Show', refine_calculator %></td>
        <td><%= link_to 'Edit', edit_refine_calculator_path(refine_calculator) %></td>
        <td><%= link_to 'Destroy', refine_calculator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Refine Calculator', new_refine_calculator_path %>

app/views/refine_calculators/new.html.erb
<h1>New Refine Calculator</h1>

<%= render 'form', refine_calculator: @refine_calculator %>

<%= link_to 'Back', refine_calculators_path %>

app/views/refine_calculators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @refine_calculator.item %>
</p>

<p>
  <strong>Value:</strong>
  <%= @refine_calculator.value %>
</p>

<p>
  <strong>Refined:</strong>
  <%= @refine_calculator.refined %>
</p>

<p>
  <strong>Refine fee:</strong>
  <%= @refine_calculator.refine_fee %>
</p>

<p>
  <strong>Transmutation fee:</strong>
  <%= @refine_calculator.transmutation_fee %>
</p>

<p>
  <strong>Url image:</strong>
  <%= @refine_calculator.url_image %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @refine_calculator.tax %>
</p>

<%= link_to 'Edit', edit_refine_calculator_path(@refine_calculator) %> |
<%= link_to 'Back', refine_calculators_path %>